--- #YAML:1.0
name:                Finance-PremiumBonds
version:             0.01
abstract:            Perl extension to check Premium Bond holder's numbers
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Precious <davidp@preshweb.co.uk>
